### ISSUE TITLE
ERC20 standard doesn't allow transfers of amounts == 0

### ISSUE THREAD

**Issue by Georgi87** [gnosis/gnosis-contracts#57]
According to the ERC20 standard are transfers of amounts == 0 not allowed and should return false:

https://theethereum.wiki/w/index.php/ERC20_Token_Standard

The code allows to do transfers of amounts == 0
https://github.com/gnosis/gnosis-contracts/blob/master/contracts/Tokens/StandardToken.sol#L46
https://github.com/gnosis/gnosis-contracts/blob/master/contracts/Tokens/StandardToken.sol#L28

**Comment by GNSPS** [comment]
@Georgi87 it's the wiki page that is wrong.

Please note here: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20-token-standard.md#transfer

**Comment by Georgi87** [comment]
Thanks for pointing this out @GNSPS. Closing the ticket. I will ask Fabian to update the wiki page.
