### ISSUE TITLE
Adding more Outcomes after a deal has started

### ISSUE THREAD

**Issue by chumMing** [gnosis/gnosis-contracts#61]
Using `event.sol` you need to know all the possible events before you deploy the contract is a little too limiting. 

Imagine if you wanted to play chess with a futarchy. You will need to have a separate token for each move that only pays out if that move happens and there is a win. You would have to have 1 round to allow people to propose moves and then you would have to take that list and reduces it so that you do not go over the `gasBlockLimit` in the for loop. Which would be quite a small list as `OutcomeTokenCreation` costs alot of gas. 

Is it possible to use the current token model to start trading and still be able to propose other moves, and distribute the associated token to the everyone that calls `buyAllOutcomes` after the fact without being prohibitively expensive?

**Comment by cag** [comment]
As you've hinted, adding outcomes to the event after creation may be expensive. As far as I understand, there is no way right now to keep track of every buyer of outcomes
 without exposing the contract to gas attacks.

Furthermore, even if this was possible, this would probably be unfair to market participants: suppose a participant wanted to go in on a position, but it wasn't expressed as an outcome, so the participant spends collateral to go in on their second best choice. Then the outcome is created, and the value of all outcomes are diluted. The participant could have waited and traded for the new outcome directly, but that would require the participant knowing the outcomes list would become modified. Also, everybody who participated in the event would have probably paid too much for their outcome tokens.

**Comment by chumMing** [comment]
>As you've hinted, adding outcomes to the event after creation may be expensive. As far as I understand, there is no way right now to keep track of every buyer of outcomes

I am preparing a possible solution and will post it here once i have time to finish it. 

>Furthermore, even if this was possible, this would probably be unfair to market participants: suppose a participant wanted to go in on a position

Well the current situation is that you deposit 1 Token (Can be ETH or WIZ or anything else) and you buy 1 Token of all outcomes. If you return all outcomes you get your 1 Token back OR if after the event you return the winning outcome you get 1 Token. 

So you give these tokens to the users and they trade them as they see fit so that they only have the outcomes they think are likely and/or profitable. But this system is broken right now because they only get the tokens for the outcomes that exist at withdraw time. If the someone deposits ETH they should always be able to withdraw extra outcomes that were created after the fact at no cost. 

I will prepare a PR for this feature.

**Comment by cag** [comment]
Closing this, as I'm still not convinced that adding outcome tokens after an event is live can be done fairly and consistently. Outcomes should account for all possibilities.
